"""Investigator stub.

Returns a deterministic placeholder diagnosis so the API surface is exercisable
end-to-end before the real LLM-backed pipeline is wired in.
"""

from __future__ import annotations

from typing import Final

from app.models import (
    AnalyzeTicketRequest,
    AnalyzeTicketResponse,
    Diagnosis,
    RecommendedAction,
)

_PLACEHOLDER_SUMMARY: Final[str] = (
    "[stub] Diagnosis will be generated by the investigator pipeline."
)


def investigate(req: AnalyzeTicketRequest) -> AnalyzeTicketResponse:
    """Run a placeholder investigation for ``req.ticket``."""
    ticket = req.ticket
    return AnalyzeTicketResponse(
        ticket_id=ticket.ticket_id,
        diagnosis=Diagnosis(
            summary=_PLACEHOLDER_SUMMARY,
            likely_root_causes=[],
            confidence=0.0,
        ),
        recommended_actions=[
            RecommendedAction(
                title="Awaiting investigator pipeline",
                rationale="Stub response — replace with real diagnosis output.",
                priority=ticket.severity,
            )
        ],
        environment=ticket.environment,
        severity=ticket.severity,
    )
